export const jazminPlanFoods = [
  { name: "Ezekiel bread", category: "carb", serving_mode: "grams", serving_label: "34 g", base_grams: 34, calories: 80, protein_g: 5, carbs_g: 15, fat_g: 0.5, fiber_g: 3 },
  { name: "Liquid egg whites", category: "protein", serving_mode: "grams", serving_label: "120 g", base_grams: 120, calories: 60, protein_g: 13, carbs_g: 0, fat_g: 0, fiber_g: 0 },
  { name: "Bone chicken broth", category: "protein", serving_mode: "grams", serving_label: "240 g", base_grams: 240, calories: 45, protein_g: 9, carbs_g: 0, fat_g: 0.5, fiber_g: 0 },
  { name: "Cottage cheese 1.5%", category: "protein", serving_mode: "grams", serving_label: "110 g", base_grams: 110, calories: 90, protein_g: 13, carbs_g: 5, fat_g: 2, fiber_g: 0 },
  { name: "Hard-boiled egg", category: "protein", serving_mode: "unit", serving_label: "1 egg", base_grams: null, calories: 70, protein_g: 6, carbs_g: 0, fat_g: 5, fiber_g: 0 },
  { name: "Protein shake + creatine", category: "protein", serving_mode: "unit", serving_label: "1 scoop", base_grams: null, calories: 135, protein_g: 25, carbs_g: 3, fat_g: 2, fiber_g: 0 },
  { name: "Chicken breast cooked", category: "protein", serving_mode: "grams", serving_label: "113 g cooked", base_grams: 113, calories: 187, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
  { name: "Cooked rice", category: "carb", serving_mode: "grams", serving_label: "100 g", base_grams: 100, calories: 130, protein_g: 3, carbs_g: 28, fat_g: 0.3, fiber_g: 0.4 },
  { name: "Avocado", category: "fat", serving_mode: "grams", serving_label: "50 g", base_grams: 50, calories: 80, protein_g: 1, carbs_g: 4, fat_g: 7, fiber_g: 3 },
  { name: "Vegetables", category: "other", serving_mode: "grams", serving_label: "100 g", base_grams: 100, calories: 25, protein_g: 2, carbs_g: 5, fat_g: 0, fiber_g: 2 },
  { name: "Olive oil", category: "fat", serving_mode: "grams", serving_label: "5 g", base_grams: 5, calories: 40, protein_g: 0, carbs_g: 0, fat_g: 4.5, fiber_g: 0 },
  { name: "Oikos Triple Zero", category: "protein", serving_mode: "grams", serving_label: "150 g", base_grams: 150, calories: 90, protein_g: 15, carbs_g: 6, fat_g: 0, fiber_g: 0 },
  { name: "Mandarin", category: "fruit", serving_mode: "unit", serving_label: "1 medium", base_grams: null, calories: 45, protein_g: 0, carbs_g: 12, fat_g: 0, fiber_g: 2 },
  { name: "Tilapia cooked", category: "protein", serving_mode: "grams", serving_label: "142 g cooked", base_grams: 142, calories: 180, protein_g: 38, carbs_g: 0, fat_g: 3, fiber_g: 0 },
  { name: "Potato cooked", category: "carb", serving_mode: "grams", serving_label: "150 g", base_grams: 150, calories: 130, protein_g: 3, carbs_g: 30, fat_g: 0, fiber_g: 3 },
  { name: "Feta", category: "fat", serving_mode: "grams", serving_label: "28 g", base_grams: 28, calories: 75, protein_g: 4, carbs_g: 1, fat_g: 6, fiber_g: 0 },
  { name: "Ground turkey 93% cooked", category: "protein", serving_mode: "grams", serving_label: "113 g cooked", base_grams: 113, calories: 170, protein_g: 22, carbs_g: 0, fat_g: 9, fiber_g: 0 },
  { name: "Cooked quinoa", category: "carb", serving_mode: "grams", serving_label: "93 g", base_grams: 93, calories: 111, protein_g: 4, carbs_g: 20, fat_g: 2, fiber_g: 2.5 },
  { name: "Pineapple", category: "fruit", serving_mode: "unit", serving_label: "1/2 cup", base_grams: null, calories: 41, protein_g: 0, carbs_g: 11, fat_g: 0, fiber_g: 1 },
  { name: "Ground beef 96% cooked", category: "protein", serving_mode: "grams", serving_label: "113 g cooked", base_grams: 113, calories: 170, protein_g: 24, carbs_g: 0, fat_g: 7, fiber_g: 0 },
  { name: "Sweet potato cooked", category: "carb", serving_mode: "grams", serving_label: "130 g", base_grams: 130, calories: 112, protein_g: 2, carbs_g: 26, fat_g: 0, fiber_g: 4 },
  { name: "Safe Catch tuna", category: "protein", serving_mode: "grams", serving_label: "113 g", base_grams: 113, calories: 90, protein_g: 24, carbs_g: 0, fat_g: 1, fiber_g: 0 },
  { name: "Cooked lentils", category: "carb", serving_mode: "grams", serving_label: "100 g", base_grams: 100, calories: 115, protein_g: 9, carbs_g: 20, fat_g: 0, fiber_g: 8 },
  { name: "Watermelon", category: "fruit", serving_mode: "unit", serving_label: "1 cup diced", base_grams: null, calories: 48, protein_g: 1, carbs_g: 12, fat_g: 0, fiber_g: 1 },
  { name: "Ahi tuna cooked", category: "protein", serving_mode: "grams", serving_label: "142 g cooked", base_grams: 142, calories: 185, protein_g: 41, carbs_g: 0, fat_g: 2, fiber_g: 0 },
  { name: "Cooked beans", category: "carb", serving_mode: "grams", serving_label: "100 g", base_grams: 100, calories: 110, protein_g: 7, carbs_g: 20, fat_g: 0.5, fiber_g: 7 },
  { name: "Fiber One brownie/cookie", category: "snack", serving_mode: "unit", serving_label: "1 item", base_grams: null, calories: 70, protein_g: 2, carbs_g: 17, fat_g: 2, fiber_g: 6 },
  { name: "Cooked pasta", category: "carb", serving_mode: "grams", serving_label: "140 g", base_grams: 140, calories: 200, protein_g: 7, carbs_g: 40, fat_g: 1, fiber_g: 2 },
  { name: "Ezekiel tortilla", category: "carb", serving_mode: "grams", serving_label: "57 g", base_grams: 57, calories: 150, protein_g: 6, carbs_g: 26, fat_g: 3.5, fiber_g: 4 },
  { name: "Banana", category: "fruit", serving_mode: "unit", serving_label: "1 medium", base_grams: null, calories: 105, protein_g: 1, carbs_g: 27, fat_g: 0, fiber_g: 3 },
] as const;

export const jazminMealTemplates = [
  { name: "Breakfast Option 1 - Lean", items: [["Ezekiel bread", 1], ["Liquid egg whites", 120], ["Bone chicken broth", 1], ["Cottage cheese 1.5%", 110]] },
  { name: "Breakfast Option 2 - Higher Fat", items: [["Ezekiel bread", 1], ["Hard-boiled egg", 2], ["Bone chicken broth", 1], ["Cottage cheese 1.5%", 110]] },
  { name: "Snack - Daily Protein Shake", items: [["Protein shake + creatine", 1]] },
  { name: "Plan A - Lunch", items: [["Chicken breast cooked", 113], ["Cooked rice", 1], ["Avocado", 1], ["Vegetables", 2], ["Olive oil", 1]] },
  { name: "Plan A - Snack 2", items: [["Oikos Triple Zero", 1], ["Mandarin", 1]] },
  { name: "Plan A - Dinner", items: [["Tilapia cooked", 142], ["Potato cooked", 1], ["Vegetables", 2], ["Olive oil", 1], ["Feta", 1]] },
  { name: "Plan B - Lunch", items: [["Ground turkey 93% cooked", 113], ["Cooked quinoa", 1], ["Avocado", 1], ["Vegetables", 2], ["Olive oil", 1]] },
  { name: "Plan B - Snack 2", items: [["Cottage cheese 1.5%", 110], ["Pineapple", 1]] },
  { name: "Plan B - Dinner", items: [["Ground beef 96% cooked", 113], ["Sweet potato cooked", 1], ["Vegetables", 2], ["Olive oil", 1], ["Feta", 1]] },
  { name: "Plan C - Lunch", items: [["Safe Catch tuna", 1], ["Cooked lentils", 1], ["Avocado", 1], ["Vegetables", 2], ["Olive oil", 1]] },
  { name: "Plan C - Snack 2", items: [["Oikos Triple Zero", 1], ["Watermelon", 1]] },
  { name: "Plan C - Dinner", items: [["Chicken breast cooked", 113], ["Cooked rice", 1], ["Avocado", 1], ["Vegetables", 2], ["Olive oil", 1]] },
  { name: "Plan D - Lunch", items: [["Ahi tuna cooked", 142], ["Cooked beans", 1], ["Avocado", 1], ["Vegetables", 2]] },
  { name: "Plan D - Snack 2", items: [["Fiber One brownie/cookie", 1], ["Oikos Triple Zero", 1]] },
  { name: "Plan D - Dinner", items: [["Ground turkey 93% cooked", 113], ["Cooked quinoa", 1], ["Avocado", 1], ["Vegetables", 2], ["Olive oil", 1]] },
  { name: "Plan E - Lunch", items: [["Ground beef 96% cooked", 113], ["Cooked pasta", 1], ["Vegetables", 2], ["Olive oil", 1]] },
  { name: "Plan E - Snack 2", items: [["Cottage cheese 1.5%", 110], ["Pineapple", 1]] },
  { name: "Plan E - Dinner", items: [["Tilapia cooked", 142], ["Sweet potato cooked", 1], ["Avocado", 1], ["Vegetables", 2]] },
  { name: "Plan F - Lunch", items: [["Chicken breast cooked", 113], ["Cooked beans", 1], ["Avocado", 1], ["Vegetables", 2]] },
  { name: "Plan F - Snack 2", items: [["Oikos Triple Zero", 1]] },
  { name: "Plan F - Dinner", items: [["Tilapia cooked", 142], ["Cooked rice", 1], ["Vegetables", 2], ["Olive oil", 1], ["Feta", 1]] },
  { name: "Plan G - Lunch", items: [["Safe Catch tuna", 1], ["Ezekiel tortilla", 1], ["Avocado", 1], ["Vegetables", 2]] },
  { name: "Plan G - Snack 2", items: [["Oikos Triple Zero", 1], ["Banana", 1]] },
  { name: "Plan G - Dinner", items: [["Ground turkey 93% cooked", 113], ["Cooked lentils", 1], ["Vegetables", 2], ["Olive oil", 1], ["Feta", 1]] },
] as const;
